export * from "./Student";
export * from "./OtpVerification";
export * from "./Course";
export * from "./StudentCourse";
export * from "./TimetableSlot";
export * from "./Assignment";
export * from "./LectureSummary";
export * from "./DocumentFile";
export * from "./GradeRecord";
